### ISSUE TITLE
It would be great if the resulting file's extension matched the target

### ISSUE THREAD

**Issue by gegles** [cbrand/gulp-protobufjs#2]
For 'amd', 'commonjs' and 'js' the extension of ".js" is great. For 'json' it should be '.json' for 'proto' a '.proto'.

Cheers. G.

**Comment by cbrand** [comment]
Ok the extension is now automatically being set to the correct file. One can pass a custom option by providing the extension to the new `ext` option.

**Comment by cbrand** [comment]
Available in [npm](https://www.npmjs.com/package/gulp-protobufjs) in Version 1.1.0.

**Comment by gegles** [comment]
You're my new hero! Thanks.

**Comment by cbrand** [comment]
You're certainly most welcome :)
