### ISSUE TITLE
Error reporting failure in unit tests

### ISSUE THREAD

**Issue by jbq** [cbrand/gulp-protobufjs#3]
I wrote a unit test in `indexSpec.js` to reproduce an issue I'm having.  When this test fails, instead of reporting a pretty error message, I'm getting the following failure:

```
  37 passing (69ms)
  1 failing

  1) index should be able to propagate syntax:
     Error: no writecb in Transform class
      at afterTransform (node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:95:33)
      at TransformState.afterTransform (node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:79:12)
      at index.js:75:13
      at _rejected (node_modules/q/q.js:844:24)
      at node_modules/q/q.js:870:30
      at Promise.when (node_modules/q/q.js:1122:31)
      at Promise.promise.promiseDispatch (node_modules/q/q.js:788:41)
      at node_modules/q/q.js:604:44
      at runSingle (node_modules/q/q.js:137:13)
      at flush (node_modules/q/q.js:125:13)



npm ERR! Test failed.  See above for more details.
```

I'm using npm 2.4.17 and node v4.2.1.  I tried various tweaks in `index.js` in the `catch` block to no avail.

Can you please help?  Thanks!

**Comment by cbrand** [comment]
I am afraid without the test I can not really help you there. It looks like there is an issue with the stream handling (aka the in-memory-files of gulp).

I would however need the test to give you any specific pointers on what might be the issue there.

**Comment by jbq** [comment]
You can see it here:
https://github.com/jbq/gulp-protobufjs/commit/fec2a07efefc79749fd4721c9b95db940d11a0ec#diff-f8527a676c6539a8c3a8deffff5dd29a

**Comment by cbrand** [comment]
Seems like you fixed it already by updating the protobufjs library :) It works fine with the current changes in your repository for me.

I am going to close this. However, I update the underlying protobuf to the newest version, due to their being new ones and there don't seem to be any issues with it. If you still have issues with your changes feel free to contact me.

**Comment by jbq** [comment]
This is still an issue for me: when a test fails, error reporting breaks

**Comment by cbrand** [comment]
I just had the chance to look into it.

Seems like I've done the error handling wrong and the error was seen as the legitimate return of the function.

Git-Commit https://github.com/cbrand/gulp-protobufjs/commit/390a4f1fa3cab6351d05de4feea945686f7b896d fixes that and you should be able to see the correct error when running the tests.
